CLASS zcl_lab_19_lion_ger DEFINITION INHERITING FROM zcl_lab_18_animal_ger
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  METHODS walk REDEFINITION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_19_lion_ger IMPLEMENTATION.
  METHOD walk.
    rv_cadena = 'The lion walks'.
  ENDMETHOD.

ENDCLASS.
