CLASS zcl_lab_31_org_france_ger DEFINITION INHERITING FROM ZCL_LAB_29_ORGANIZATION_GER
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

     METHODS get_location REDEFINITION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_31_org_france_ger IMPLEMENTATION.
  METHOD get_location.
    rv_location = 'FRANCE'.
  ENDMETHOD.

ENDCLASS.
