CLASS zcl_lab_12_linux_ger DEFINITION INHERITING FROM ZCL_LAB_11_SYSTEM_GER
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_12_linux_ger IMPLEMENTATION.
ENDCLASS.
