CLASS zcl_lab_30_org_germany_ger DEFINITION INHERITING FROM ZCL_LAB_29_ORGANIZATION_GER
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

   METHODS get_location REDEFINITION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_30_org_germany_ger IMPLEMENTATION.
  METHOD get_location.
    rv_location = 'GERMANY'.
  ENDMETHOD.

ENDCLASS.
